# HR Analytics — Employee Attrition & Performance

## 1. Data Understanding

### Objective
The objective of this phase is to understand the HR dataset, its structure, column names, data types, and overall data quality before performing data cleaning and analysis.

### Dataset Overview
The dataset contains employee-related information that can help us analyze employee attrition and identify patterns in the workforce.

### Activities Performed
1. Load the dataset using Pandas.
2. Display the first five records.
3. Identify the number of rows and columns.
4. Examine the column names.
5. Understand the data types and non-null values.
6. Generate descriptive statistics.
7. Check for missing values.
8. Check for duplicate records.
9. Examine the distribution of employee attrition.

### Tools and Libraries
- Python
- Pandas
- Jupyter Notebook

### Expected Outcome
Understand the dataset's structure, identify potential data quality issues, and prepare for the data cleaning phase.

### Next Step
Data Cleaning and Preprocessing.

In [2]:
import pandas as pd

df = pd.read_csv("../data/raw/hr_analytics_raw.csv")

print("Data loaded successfully")
print("Rows and Columns:", df.shape)

df.head()

Data loaded successfully
Rows and Columns: (1530, 12)

,EmployeeID,Age,Gender,Department,JobRole,MonthlyIncome,YearsAtCompany,JobSatisfaction,Attrition,Overtime,PerformanceRating,EducationLevel
0,EMP00739,42,Female,Customer Support,Support Agent,34364,22,Medium,No,No,Needs Improvement,PhD
1,EMP00360,23,Female,IT,IT Support,40000,5,Medium,No,No,Exceeds Expectations,High School
2,EMP00807,52,Female,Operations,Operations Analyst,28302,27,Very High,No,Yes,Needs Improvement,Bachelor's
3,EMP00596,39,Male,Customer Support,Support Agent,11010,10,High,No,True,Needs Improvement,Master's
4,EMP00228,29,Male,Research & Development,Research Scientist,15678,7,Medium,No,No,Exceeds Expectations,PhD

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1530 entries, 0 to 1529
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   EmployeeID         1530 non-null   str
 1   Age                1505 non-null   str
 2   Gender             1511 non-null   str
 3   Department         1508 non-null   str
 4   JobRole            1513 non-null   str
 5   MonthlyIncome      1493 non-null   str
 6   YearsAtCompany     1500 non-null   str
 7   JobSatisfaction    1510 non-null   str
 8   Attrition          1516 non-null   str
 9   Overtime           1517 non-null   str
 10  PerformanceRating  1515 non-null   str
 11  EducationLevel     1520 non-null   str
dtypes: str(12)
memory usage: 143.6 KB

In [4]:
missing_values=df.isnull().sum()
print("Missing values in each column:")
print(missing_values)

Missing values in each column:
EmployeeID            0
Age                  25
Gender               19
Department           22
JobRole              17
MonthlyIncome        37
YearsAtCompany       30
JobSatisfaction      20
Attrition            14
Overtime             13
PerformanceRating    15
EducationLevel       10
dtype: int64

Why this matters: Counts tell us how many values are missing; percentages tell us how much of each column is affected.

In [5]:
missing_values=df.isnull().sum()
missing_percentage=missing_values/len(df)*100
print("MISSING PERCENTAGE:")
print(missing_percentage)

MISSING PERCENTAGE:
EmployeeID           0.000000
Age                  1.633987
Gender               1.241830
Department           1.437908
JobRole              1.111111
MonthlyIncome        2.418301
YearsAtCompany       1.960784
JobSatisfaction      1.307190
Attrition            0.915033
Overtime             0.849673
PerformanceRating    0.980392
EducationLevel       0.653595
dtype: float64

In [6]:
print("Duplicated records:")
print(df.duplicated().sum())

Duplicated records:
30

In [7]:
# df.duplicated() identifies rows that exactly repeat an earlier row.
# df[df.duplicated()] displays those repeated rows.
# .head(10) displays up to 10 rows for inspection.

In [8]:
duplicated_rows=df[df.duplicated()]
duplicated_rows.head(10)

,EmployeeID,Age,Gender,Department,JobRole,MonthlyIncome,YearsAtCompany,JobSatisfaction,Attrition,Overtime,PerformanceRating,EducationLevel
230,EMP00296,31 years,Male,Finance,Accountant,11872,13,High,Yes,No,Needs Improvement,Master's
259,EMP00913,36,Male,Operations,Operations Manager,16711,11,High,No,Yes,Exceeds Expectations,PhD
386,EMP00821,28,Non-binary,Finance,Accountant,22069,6,Low,No,Yes,Meets Expectations,Master's
551,EMP00617,NaN,Female,Operations,Operations Manager,40000,23,High,Yes,Yes,Needs Improvement,Master's
594,EMP00043,24,Non-binary,Human Resources,HR Manager,40000,6,Low,Yes,Yes,Exceeds Expectations,High School
605,EMP00142,34 years,Female,Customer Support,Support Manager,15395,2,Very High,No,No,Exceeds Expectations,Master's
656,EMP00972,41,Male,Customer Support,Support Agent,40000,21,Low,Yes,Yes,Exceeds Expectations,Bachelor's
757,EMP00058,31,Female,Ops,Coordinator,32241,8,Medium,No,No,Meets Expectations,Bachelor's
822,EMP00390,35,Male,Sales,Sales Representative,NaN,16,Very High,No,No,Meets Expectations,High School
990,EMP00720,46,Male,Research & Development,Research Scientist,32839,NaN,High,No,No,Meets Expectations,Master's

In [9]:
print("rows involved in duplicate groups:",df.duplicated(keep=False).sum())

rows involved in duplicate groups: 60

In [10]:
df[df.duplicated(keep=False)].head(20)

,EmployeeID,Age,Gender,Department,JobRole,MonthlyIncome,YearsAtCompany,JobSatisfaction,Attrition,Overtime,PerformanceRating,EducationLevel
0,EMP00739,42,Female,Customer Support,Support Agent,34364,22,Medium,No,No,Needs Improvement,PhD
21,EMP00058,31,Female,Ops,Coordinator,32241,8,Medium,No,No,Meets Expectations,Bachelor's
46,EMP00720,46,Male,Research & Development,Research Scientist,32839,NaN,High,No,No,Meets Expectations,Master's
64,EMP00972,41,Male,Customer Support,Support Agent,40000,21,Low,Yes,Yes,Exceeds Expectations,Bachelor's
131,EMP00913,36,Male,Operations,Operations Manager,16711,11,High,No,Yes,Exceeds Expectations,PhD
170,EMP00821,28,Non-binary,Finance,Accountant,22069,6,Low,No,Yes,Meets Expectations,Master's
173,EMP01219,44,Female,Sales,Sales Manager,29051,26,Medium,No,Yes,Needs Improvement,PhD
179,EMP01493,30,Female,Human Resources,HR Manager,29753,12,High,No,No,Needs Improvement,High School
191,EMP00296,31 years,Male,Finance,Accountant,11872,13,High,Yes,No,Needs Improvement,Master's
230,EMP00296,31 years,Male,Finance,Accountant,11872,13,High,Yes,No,Needs Improvement,Master's
257,EMP00043,24,Non-binary,Human Resources,HR Manager,40000,6,Low,Yes,Yes,Exceeds Expectations,High School
259,EMP00913,36,Male,Operations,Operations Manager,16711,11,High,No,Yes,Exceeds Expectations,PhD
265,EMP00142,34 years,Female,Customer Support,Support Manager,15395,2,Very High,No,No,Exceeds Expectations,Master's
308,EMP01040,19,Non-binary,Research & Development,Research Director,40000,2,Very High,No,No,Exceeds Expectations,Bachelor's
330,EMP00939,18,Female,IT,IT Support,19290,1,High,NO,No,Meets Expectations,PhD
373,EMP00390,35,Male,Sales,Sales Representative,NaN,16,Very High,No,No,Meets Expectations,High School
381,EMP01048,29,Female,Research & Development,Research Scientist,34577,10,High,No,No,Meets Expectations,High School
386,EMP00821,28,Non-binary,Finance,Accountant,22069,6,Low,No,Yes,Meets Expectations,Master's
389,EMP00317,36,Male,Research & Development,Research Scientist,16296,17,Very High,No,No,Meets Expectations,Master's
448,EMP01050,38,Male,Sales,Sales Executive,NaN,14,Low,Yes,Yes,Exceeds Expectations,PhD

In [11]:
print("Number of duplicates involved:", df.duplicated(keep=False).sum())

Number of duplicates involved: 60

In [12]:
print("Unique Employee IDs:", df["EmployeeID"].nunique())
print("Duplicate Employee IDs:", df["EmployeeID"].duplicated().sum())

Unique Employee IDs: 1500
Duplicate Employee IDs: 30

In [13]:
print("Gender Distribution:")
print(df["Gender"].value_counts(dropna=False))
#THIS MEANS IT WILL COUNT NAN VALUES ALSO

Gender Distribution:
Gender
Male            503
Female          499
Non-binary      468
NaN              19
 Male             7
 Female           7
non-binary        6
NON-BINARY        5
male              5
FEMALE            4
MALE              4
 Non-binary       3
Name: count, dtype: int64

In [14]:
print("Department Distribution:")
print(df["Department"].value_counts(dropna=False))

Department Distribution:
Department
Research & Development      217
Sales                       211
IT                          203
Finance                     203
Human Resources             198
Operations                  194
Customer Support            193
NaN                          22
Ops                          10
it                            8
customer support              8
R&D                           7
I.T.                          7
finance                       7
research and development      6
human resources               6
 FINANCE                      5
Research & development        5
Cust Support                  4
sales                         4
 SALES                        3
HR                            2
OPERATIONS                    2
Customer service              2
Human resources               1
Sale                          1
operations                    1
Name: count, dtype: int64

In [15]:
print("Employee Attrition Distribution:")
print(df["Attrition"].value_counts(dropna=False))

Employee Attrition Distribution:
Attrition
No       1190
Yes       283
NaN        14
N           9
False       9
NO          8
 No         6
no          5
yes         2
 Yes        2
YES         2
Name: count, dtype: int64

In [16]:
print("Overtime Distribution:")
print(df["Overtime"].value_counts(dropna=False))

Overtime Distribution:
Overtime
No       783
Yes      695
NaN       13
NO         7
 Yes       5
yes        5
YES        5
N          4
Y          3
no         3
True       2
 No        2
False      2
y          1
Name: count, dtype: int64

In [17]:
print("Job Role Distribution:")
print(df["JobRole"].value_counts(dropna=False))

Job Role Distribution:
JobRole
Research Director       82
IT Support              81
Operations Analyst      80
Recruiter               79
Accountant              77
Sales Executive         77
Lab Technician          77
Research Scientist      76
Sales Representative    75
Support Manager         74
Team Lead               72
Financial Analyst       70
Software Engineer       70
Finance Manager         69
Sales Manager           69
Coordinator             67
Data Analyst            67
HR Executive            65
HR Manager              63
Operations Manager      62
Support Agent           61
NaN                     17
Name: count, dtype: int64

In [18]:
print("Performance Rating Distribution:")
print(df["PerformanceRating"].value_counts(dropna=False))

Performance Rating Distribution:
PerformanceRating
Needs Improvement         518
Meets Expectations        501
Exceeds Expectations      458
NaN                        15
needs improvement           7
 Needs Improvement          6
 Exceeds Expectations       5
EXCEEDS EXPECTATIONS        4
 Meets Expectations         4
NEEDS IMPROVEMENT           3
MEETS EXPECTATIONS          3
exceeds expectations        3
meets expectations          2
 exceeds expectations       1
Name: count, dtype: int64

In [19]:
print("Education Level Distribution:")
print(df["EducationLevel"].value_counts(dropna=False))

Education Level Distribution:
EducationLevel
Master's         385
High School      378
PhD              377
Bachelor's       341
NaN               10
BACHELOR'S         5
phd                4
PHD                4
high school        4
MASTER'S           4
bachelor's         4
 High School       3
 PhD               3
HIGH SCHOOL        3
 Master's          2
 Bachelor's        1
master's           1
 MASTER'S          1
Name: count, dtype: int64

In [20]:
print("Age Distribution:")
print(df["Age"].value_counts(dropna=False).head(20))

Age Distribution:
Age
38    65
35    64
31    62
28    61
34    59
37    59
41    59
33    58
32    56
30    56
40    55
39    52
18    52
36    52
44    51
29    49
42    48
23    45
26    42
45    36
Name: count, dtype: int64

In [21]:
print("Age values containing non-numeric characters:")
print(df.loc[
          df["Age"].notna() & ~df["Age"].str.strip().str.fullmatch(r"\d+"),
          "Age"
      ].value_counts())

Age values containing non-numeric characters:
Age
26 years    5
31 years    4
34 years    4
36 years    3
47 years    3
43 years    3
28 years    3
40 years    2
30 years    2
23 years    1
22 years    1
27 years    1
41 years    1
18 years    1
37 years    1
39 years    1
44 years    1
46 years    1
32 years    1
42 years    1
45 years    1
35 years    1
33 years    1
Name: count, dtype: int64

In [22]:
print("Monthly Income Distribution:")
print(df["MonthlyIncome"].value_counts().head(20))

Monthly Income Distribution:
MonthlyIncome
40000        290
999999         4
₹40,000        4
40000 INR      4
-500           4
19290          3
40,000         3
34364          2
16877          2
32241          2
23702          2
18517          2
32839          2
38101          2
36049          2
11724          2
16711          2
22069          2
22875          2
29051          2
Name: count, dtype: int64

In [23]:
print(df.loc[
          df["MonthlyIncome"].str.contains(r"[^\d]", na=False),
          "MonthlyIncome"
      ].value_counts())

MonthlyIncome
₹40,000      4
40000 INR    4
-500         4
40,000       3
₹999,999     2
34,044       1
22808 INR    1
13,193       1
19,522       1
13372 INR    1
9,832        1
14,847       1
14,458       1
₹31,951      1
28,397       1
32122 INR    1
23966 INR    1
₹12,924      1
13470 INR    1
24997 INR    1
22462 INR    1
₹16,352      1
34814 INR    1
₹28,192      1
24831 INR    1
₹29,111      1
28,870       1
8,848        1
12,460       1
₹36,964      1
₹34,340      1
24101 INR    1
8,495        1
20014 INR    1
22169 INR    1
32,838       1
18390 INR    1
₹14,531      1
33,053       1
24360 INR    1
31,556       1
30470 INR    1
24193 INR    1
35,780       1
16,322       1
₹27,926      1
24,663       1
20125 INR    1
Name: count, dtype: int64

In [24]:
print("Monthly Income values containing non-numeric characters:")
print(df.loc[
          df["MonthlyIncome"].notna()
          & ~df["MonthlyIncome"].str.strip().str.fullmatch(r"\d+"),
          "MonthlyIncome"
      ].value_counts().head(20))

Monthly Income values containing non-numeric characters:
MonthlyIncome
₹40,000      4
40000 INR    4
-500         4
40,000       3
₹999,999     2
34,044       1
22808 INR    1
13,193       1
19,522       1
13372 INR    1
9,832        1
14,847       1
14,458       1
₹31,951      1
28,397       1
32122 INR    1
23966 INR    1
₹12,924      1
13470 INR    1
24997 INR    1
Name: count, dtype: int64

In [25]:
print("Years at a company")
print(df["YearsAtCompany"].value_counts(dropna=False).sort_index())

Years at a company
YearsAtCompany
 12        1
 18        1
 24        1
 3         1
 6         2
 7         1
 8         2
 9         1
-2         2
0        112
1        126
10        60
11        67
12        48
13        47
14        43
15        44
16        22
17        44
18        28
19        22
2         95
20        30
21        19
22        16
23        21
24        14
25        14
26         9
27         6
28         8
29         5
3         90
3 yrs     11
30         7
4         69
45         4
5         86
6         88
7         80
8         67
9         65
five      20
forty      1
NaN       30
Name: count, dtype: int64

In [26]:
print(df.loc[~df["YearsAtCompany"].str.strip().str.contains(r"[^\d]", na=False),].value_counts(dropna=False))

EmployeeID  Age  Gender      Department              JobRole             MonthlyIncome  YearsAtCompany  JobSatisfaction  Attrition  Overtime  PerformanceRating     EducationLevel
EMP00739    42   Female      Customer Support        Support Agent       34364          22              Medium           No         No        Needs Improvement     PhD               2
EMP00058    31   Female      Ops                     Coordinator         32241          8               Medium           No         No        Meets Expectations    Bachelor's        2
EMP00720    46    Male       Research & Development  Research Scientist  32839          NaN             High             No         No        Meets Expectations    Master's          2
EMP00972    41   Male        Customer Support        Support Agent       40000          21              Low              Yes        Yes       Exceeds Expectations  Bachelor's        2
EMP00913    36   Male        Operations              Operations Manager  16711          11              High             No         Yes       Exceeds Expectations  PhD               2
                                                                                                                                                                                     ..
EMP00078    34   Female      Finance                 Accountant          27565          3               LOW              No         Yes       Meets Expectations    Bachelor's        1
EMP00953    26   Non-binary  Human Resources         Recruiter           11926          6               Very High        Yes        Yes       Meets Expectations    High School       1
EMP00795    39   Male        Human Resources         HR Executive        16877          6               Very High        No         Yes       Meets Expectations    High School       1
EMP01415    33   Male        IT                      IT Support          15128          6               Very High        No         No        Exceeds Expectations  High School       1
EMP00258    30   Female      Research & Development  Research Scientist  12256          0               Very High        Yes        No        Meets Expectations    High School       1
Name: count, Length: 1466, dtype: int64

In [27]:
print(df.loc[
          ~df["YearsAtCompany"].str.strip().str.fullmatch(r"\d+", na=False),
          "YearsAtCompany"
      ].value_counts(dropna=False))

YearsAtCompany
NaN      30
five     20
3 yrs    11
-2        2
forty     1
Name: count, dtype: int64

In [28]:
print("Job satisfaction distribution")
print(df["JobSatisfaction"].value_counts(dropna=False))

Job satisfaction distribution
JobSatisfaction
Very High      386
Low            373
High           363
Medium         348
NaN             20
 High            6
medium           5
LOW              5
VERY HIGH        4
HIGH             4
 Low             3
 Very High       3
low              3
very high        2
high             2
MEDIUM           1
 Medium          1
 LOW             1
Name: count, dtype: int64

In [29]:
# Explanation: This code checks whether JobSatisfaction contains only the four expected categories: Low, Medium, High, and Very High. It ignores capitalization and removes extra spaces. The ~ selects values that don't match, while value_counts(dropna=False) counts them, including missing values. The output shows 20 missing values and no other unexpected categories.

In [30]:
print(df.loc[
          ~df["JobSatisfaction"].str.strip().str.fullmatch(
              r"(?i)low|medium|high|very high", na=False
          ),
          "JobSatisfaction"
      ].value_counts(dropna=False))

JobSatisfaction
NaN    20
Name: count, dtype: int64

In [31]:
print(df.loc[
          ~df["Attrition"].str.strip().str.fullmatch(
              r"(?i)yes|no", na=False
          ),
          "Attrition"
      ].value_counts(dropna=False))

Attrition
NaN      14
N         9
False     9
Name: count, dtype: int64

In [32]:
print(df["Attrition"].value_counts(dropna=False))

Attrition
No       1190
Yes       283
NaN        14
N           9
False       9
NO          8
 No         6
no          5
yes         2
 Yes        2
YES         2
Name: count, dtype: int64

In [33]:
print(df["Overtime"].value_counts(dropna=False))

Overtime
No       783
Yes      695
NaN       13
NO         7
 Yes       5
yes        5
YES        5
N          4
Y          3
no         3
True       2
 No        2
False      2
y          1
Name: count, dtype: int64

In [34]:
print(df.loc[
          ~df["Overtime"].str.strip().str.fullmatch(
              r"(?i)yes|no", na=False
          ),
          "Overtime"
      ].value_counts(dropna=False))

Overtime
NaN      13
N         4
Y         3
True      2
False     2
y         1
Name: count, dtype: int64

In [35]:
print(df["Age"].value_counts(dropna=False).sort_index())

Age
120          2
15           3
16           4
18          52
18 years     1
            ..
61           1
62           4
75           2
89           1
NaN         25
Name: count, Length: 73, dtype: int64

In [36]:
print(df.loc[~df["Age"].str.strip().str.fullmatch(r"\d+",na=False),"Age"].value_counts(dropna=False))

Age
NaN         25
26 years     5
31 years     4
34 years     4
36 years     3
47 years     3
43 years     3
28 years     3
40 years     2
30 years     2
23 years     1
22 years     1
27 years     1
41 years     1
18 years     1
37 years     1
39 years     1
44 years     1
46 years     1
32 years     1
42 years     1
45 years     1
35 years     1
33 years     1
Name: count, dtype: int64

In [37]:
print(df["Age"].value_counts(dropna=False))

Age
38          65
35          64
31          62
28          61
34          59
            ..
45 years     1
89           1
35 years     1
33 years     1
61           1
Name: count, Length: 73, dtype: int64

In [38]:
print(df.loc[pd.to_numeric(df["Age"].str.replace( " years ","",regex=False),errors="coerce").isin([15,120]),"Age"].value_counts(dropna=False))

Age
15     3
120    2
Name: count, dtype: int64

In [39]:
print(df["MonthlyIncome"].value_counts(dropna=False))

MonthlyIncome
40000        290
NaN           37
999999         4
₹40,000        4
40000 INR      4
            ...
12988          1
27565          1
11926          1
15128          1
12256          1
Name: count, Length: 1148, dtype: int64

In [40]:
income = pd.to_numeric(
    df["MonthlyIncome"].str.replace(r"[₹,]| INR", "", regex=True),
    errors="coerce"
)
print(income.describe())

count      1493.000000
mean      30709.096450
std       62379.237104
min        -500.000000
25%       18556.000000
50%       26458.000000
75%       36922.000000
max      999999.000000
Name: MonthlyIncome, dtype: float64

In [41]:
print(df["PerformanceRating"].value_counts(dropna=False))

PerformanceRating
Needs Improvement         518
Meets Expectations        501
Exceeds Expectations      458
NaN                        15
needs improvement           7
 Needs Improvement          6
 Exceeds Expectations       5
EXCEEDS EXPECTATIONS        4
 Meets Expectations         4
NEEDS IMPROVEMENT           3
MEETS EXPECTATIONS          3
exceeds expectations        3
meets expectations          2
 exceeds expectations       1
Name: count, dtype: int64

In [42]:
print(df["Gender"].value_counts(dropna=False))

Gender
Male            503
Female          499
Non-binary      468
NaN              19
 Male             7
 Female           7
non-binary        6
NON-BINARY        5
male              5
FEMALE            4
MALE              4
 Non-binary       3
Name: count, dtype: int64

In [43]:
print(df["Department"].value_counts(dropna=False))

Department
Research & Development      217
Sales                       211
IT                          203
Finance                     203
Human Resources             198
Operations                  194
Customer Support            193
NaN                          22
Ops                          10
it                            8
customer support              8
R&D                           7
I.T.                          7
finance                       7
research and development      6
human resources               6
 FINANCE                      5
Research & development        5
Cust Support                  4
sales                         4
 SALES                        3
HR                            2
OPERATIONS                    2
Customer service              2
Human resources               1
Sale                          1
operations                    1
Name: count, dtype: int64

## Key Findings

1. Dataset contains 1,530 rows and 12 columns.
2. Missing values exist across multiple columns.
3. 30 exact duplicate rows were identified.
4. Employee IDs have 30 duplicate entries.
5. Several columns contain inconsistent formatting and category labels.
6. Age contains missing values, text-formatted ages, and unusual values such as 15 and 120.
7. MonthlyIncome contains missing values, inconsistent formats, negative values, and unusually high values.
8. YearsAtCompany contains missing values, negative values, and text-formatted values.
9. Attrition and Overtime contain inconsistent labels that require verification.
10. JobSatisfaction, PerformanceRating, Gender, Department, and EducationLevel contain inconsistent capitalization or spacing.
11. Data cleaning is required before performing HR attrition analysis.